-- {{
--     config(
--         fail_calc = 'source_rows',
--         error_if = 'source_rows' == 'captured_rows'
--     )
-- }}


-- with 
-- source as(
--     select 
--             count(PROFIT_CENTER) as source_rows 
--     from 
--             {{ source('sail', 'raw_sales_data') }}
-- ), 
-- captured as(
--     select 
--             count(row_id) as captured_rows 
--     from 
--             {{ ref('stg_initial') }}
-- ),
-- final as(
--     select * from source,captured
-- )
-- select * from final